//Gallery
export const SET_POSTS = "SET_POSTS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";
export const SET_TODAY_PHOTO = "SET_TODAY_PHOTO";
export const FETCH_TODAY_PHOTO_FAILED = "FETCH_TODAY_PHOTO_FAILED";
export const SET_PHOTO = "SET_PHOTO";
export const FETCH_PHOTO_FAILED = "FETCH_PHOTO_FAILED";
export const LOADING = "LOADING";

export const SET_IMAGE_AND_VIDEO = "SET_IMAGE_AND_VIDEO";
export const FETCH_IMAGE_AND_VIDEO_FAILED = "FETCH_IMAGE_AND_VIDEO_FAILED";

export const SHOW_IMAGE_DETAIL = "SHOW_IMAGE_DETAIL";

//Learn
export const SET_ARTICLES = "SET_ARTICLES";
export const FETCH_ARTICLES_FAILED = "FETCH_ARTICLES_FAILED";
export const SELECT_ARTICLE = "SELECT_ARTICLE";
export const SET_SINGLE_ARTICLE = "SET_SINGLE_ARTICLE";
export const FETCH_SINGLE_ARTICLE_FAILED = "FETCH_SINGLE_ARTICLE_FAILED";
