export const SET_POSTS = "SET_POSTS";
export const FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED";
export const SET_TODAY_PHOTO = "SET_TODAY_PHOTO";
export const FETCH_TODAY_PHOTO_FAILED = "FETCH_TODAY_PHOTO_FAILED";
export const SET_PHOTO = "SET_PHOTO";
export const FETCH_PHOTO_FAILED = "FETCH_PHOTO_FAILED";
export const LOADING = "LOADING";
